### ISSUE TITLE
Some Problem with the UI

### ISSUE THREAD

**Issue by Adarsh-Saurabh** [Adarsh-Saurabh/Stone-Paper-Scissor-Model-Deployment#13]
![image](https://github.com/Adarsh-Saurabh/Stone-Paper-Scissor-Model-Deployment/assets/75805225/1419903a-418d-4e83-85c9-2b983e180c69)

**Comment by Adarsh-Saurabh** [comment]
@Virtual4087

**Comment by Virtual4087** [comment]
let me check
