### ISSUE TITLE
A problem with score counting

### ISSUE THREAD

**Issue by Adarsh-Saurabh** [Adarsh-Saurabh/Stone-Paper-Scissor-Model-Deployment#3]

**Comment by ghost** [comment]
I would like to work on this project if you can explain me more about the issue on this project.

**Comment by Adarsh-Saurabh** [comment]
> I would like to work on this project if you can explain me more about the issue on this project.


There is a small error with the points counting. If we won a match (+1) and then lose the match(-1) the total score should be 0 but it would be -2 according to this.

**Comment by Adarsh-Saurabh** [comment]
> I would like to work on this project if you can explain me more about the issue on this project.


I have assigned this issue to you 😁.

**Comment by shubhamatkal** [comment]
assign me this topic, i went through code and I think I can resolve it , thanks

**Comment by Adarsh-Saurabh** [comment]
Yes sure @shubhamatkal you may work on this issue.
